
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dailyfresh

mybatis-plus:
  type-aliases-package: com.jy.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
server:
  port: 8989
  servlet:
    session:
      timeout: 1